import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'API Documentation',
      items: [
        "api-docs/intro",
        {
          type: 'category',
          label: 'HTTP Сервисы',
          link: {type: 'doc', id: 'api-docs/http-services/index'},
          items: [
            "api-docs/http-services/schedule",
            "api-docs/http-services/appointment-create",
            "api-docs/http-services/appointment-status",
            "api-docs/http-services/appointment-cancel",
            "api-docs/http-services/dictionary-data",
            "api-docs/http-services/reservation",
          ]
        },
        {
          type: 'category',
          label: 'Веб-сервисы',
          link: {type: 'generated-index'},
          items: [
            {
              type: 'autogenerated',
              dirName: 'api-docs/web-services',
            }
          ]
        }
      ]
    }
  ],

  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  // tutorialSidebar: [
  //   'intro',
  //   'hello',
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: ['tutorial-basics/create-a-document'],
  //   },
  // ],
};

export default sidebars;
