import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    docs: [
        {
            type: 'category',
            label: 'Документация API',
            items: [
                "index",
                {
                    type: 'category',
                    label: 'HTTP Сервисы',
                    link: {type: 'doc', id: 'http-services/index'},
                    items: [
                        "http-services/schedule",
                        "http-services/appointment-create",
                        "http-services/appointment-status",
                        "http-services/appointment-cancel",
                        "http-services/dictionary-data",
                        "http-services/reservation",
                    ]
                },
                {
                    type: 'category',
                    label: 'Веб-сервисы 1С',
                    link: {type: 'generated-index', slug: "web-services"},
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'web-services',
                        }
                    ]
                }
            ]
        }
    ],
};

export default sidebars;
